version: '3.8'
services:
  # Web service
  web:
    image: web-sv
    container_name: web-sv
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000

  # API service
  api:
    image: api-sv
    container_name: api-sv
    build:
      context: ./API
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000

  # Database service
  db:
    image: postgres:latest
    container_name: postgres-sv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    
  # Redis service
  redis:
    image: redis:latest
    container_name: redis-sv
    ports:
      - 6379:6379