# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# WORKDIR /app

# COPY *.csproj ./
# RUN dotnet restore

# COPY . ./

# # Publish the application
# RUN dotnet publish -c Release -o out

# # Build the runtime image
# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
# WORKDIR /app
# COPY --from=build /app/out .


# Start the application
# ENTRYPOINT ["dotnet", "API.dll"]



# Use the SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

# Start the application with watch mode
CMD ["dotnet", "watch", "run", "--project", "API.csproj", "--urls", "https://*:443;http://+:5000"]
